### ISSUE TITLE
Question: Target name

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#10]
Related: #9 
Related: https://github.com/ElixirSeattle/xebow/commit/96c4fa85f9b37418ae953472884ac22d8c70a4a3#diff-6023be6004fce4718dad3dafb576d258L6

@doughsay I noticed after PR #9 was merged the hardware target name was changed from `keybow` to `kebow` (without the `y`). Just want to point out that [Keybow](https://shop.pimoroni.com/products/keybow?variant=21246333419603), the product, does have a `y` in it. Or are you going for _this_ [Kebow](https://www.urbandictionary.com/define.php?term=Kebow)? :stuck_out_tongue_winking_eye: 

It just threw me off when building the firmware, so thought I'd point it out. Am I missing something about why the name ended up the way it is now?

**Comment by doughsay** [comment]
O. M. G. are you serious?  I'm such a dummy!  UGH I gotta rename a lot of things now...  I guess I got confused because `xebow` doesn't have the y in it... but then again I made that name up too so maybe I'm just bad at naming things ;)

**Comment by amclain** [comment]
:heart: 

This is what peer review is for, right? :wink:

**Comment by doughsay** [comment]
Fixed in #18
