### ISSUE TITLE
Refactor: Cycling to a previous or next animation is the application's responsibility

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#36]
The `Engine` currently contains functionality for cycling to the `previous_animation` and `next_animation` (shown below). However, in the [2020-06-23 meeting](https://github.com/ElixirSeattle/xebow/wiki/Meeting-Notes-%282020-06-23%29#pr-33---refactor-separate-the-render-engine-from-the-hardware) we realized these are responsibilities of the application rather than the rendering engine. Therefore, we should move this code out of `Engine`, leaving the engine with the `play_animation` function for the application to tell the engine which animation should currently be playing.

https://github.com/ElixirSeattle/xebow/blob/e5589fdec01278b23f043fea198c164ce97eed01/lib/xebow/engine.ex#L31-L45

**Comment by doughsay** [comment]
This was sorta done, should we close this ticket?  Or should we change this ticket to reflect that we're still not happy with the functionality being inside the Keys server?

**Comment by amclain** [comment]
I think we can close it. The keys server is a different topic.

Resolved in #50.
