### ISSUE TITLE
Animation Config Refactor

### ISSUE THREAD

**Issue by doughsay** [ElixirSeattle/xebow#63]
We need a second pass at animation configuration:

* [x] Make it so `use Animation` is all you need and can use the `field` macros directly.
* [x] Clean up the DSL macros so they work right (i.e. so you can use things like module attributes when using them)
* [x] Somehow have definable documentation per field that the live-view UI can use

**Comment by vanvoljg** [comment]
PR #106 fixes two of these items, but I still need to look into how to get module attributes to work with a macro.
