### ISSUE TITLE
Refactor casting in Animation.Config module

### ISSUE THREAD

**Issue by vanvoljg** [ElixirSeattle/xebow#84]
There are a couple TODO notes for refactoring the casting logic in `RGBMatrix.Animation.Config`. @amclain, I think you had a suggestion for how we could do this, didn't you?

- [ ] TODO: better key casting ([lib/rgb_matrix/animation/config.ex#L77](https://github.com/ElixirSeattle/xebow/blob/626c7cb7ac5c818f51856e5b216df7f79351e459/lib/rgb_matrix/animation/config.ex#L77))
- [ ] TODO: better value casting ([lib/rgb_matrix/animation/config.ex#L80](https://github.com/ElixirSeattle/xebow/blob/626c7cb7ac5c818f51856e5b216df7f79351e459/lib/rgb_matrix/animation/config.ex#L80))

**Comment by amclain** [comment]
This is a duplicate of #70. I recommend we close this issue and move the checkboxes to the other one.

> @amclain, I think you had a suggestion for how we could do this, didn't you?

I made a comment to log the tech debt in the PR: https://github.com/ElixirSeattle/xebow/pull/56#discussion_r450604591

I also jotted down some pseudo-code for `cast`, which I believe was implemented: https://github.com/ElixirSeattle/xebow/pull/54#discussion_r451964036

**Comment by vanvoljg** [comment]
I thought it was somewhere, but missed it in the list. Thanks.
